name: LinearRegressionApp
description: Shiny App to Learn How a Regression Analysis Works
dev_path: apps
status: active
role: project
tags:
  - apps
language: R
setup:
  - Rscript app.R
env: []
services: []
depends_on: []
workspace: []
update_strategy: []
priority: []
